Fixed a problem with missing hostname in the destination
Commands like

vagrant scp file /home/vagrant/

were failing with error

scp.rb:19:in `execute': undefined method `empty?' for nil:NilClass
(NoMethodError)

due to the variable host being null